[2025-08-04T21:50:31.881+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-04T21:50:31.905+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-05T00:00:00+00:00 [queued]>
[2025-08-04T21:50:31.914+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-05T00:00:00+00:00 [queued]>
[2025-08-04T21:50:31.915+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-04T21:50:31.936+0000] {taskinstance.py:2890} INFO - Executing <Task(ArtistProduceOperator): generator_artist_data> on 2025-01-05 00:00:00+00:00
[2025-08-04T21:50:31.949+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7190) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-04T21:50:31.950+0000] {standard_task_runner.py:72} INFO - Started process 7212 to run task
[2025-08-04T21:50:31.948+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'artist_generator', 'generator_artist_data', 'scheduled__2025-01-05T00:00:00+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/artist_generator.py', '--cfg-path', '/tmp/tmpqlybys6c']
[2025-08-04T21:50:31.951+0000] {standard_task_runner.py:105} INFO - Job 236: Subtask generator_artist_data
[2025-08-04T21:50:32.022+0000] {task_command.py:467} INFO - Running <TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-05T00:00:00+00:00 [running]> on host c4e4284cebf8
[2025-08-04T21:50:32.125+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='artist_generator' AIRFLOW_CTX_TASK_ID='generator_artist_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-05T00:00:00+00:00'
[2025-08-04T21:50:32.130+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-04T21:50:32.238+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:32.348+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 19092)]>: Broker version identified as 2.6
[2025-08-04T21:50:32.374+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Connection complete.
[2025-08-04T21:50:33.406+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:35.378+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: Connection complete.
[2025-08-04T21:50:35.384+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. 
[2025-08-04T21:50:35.408+0000] {conn.py:1174} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: Error receiving network data closing socket
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/conn.py", line 1157, in _recv
    data = self._sock.recv(self.config['sock_chunk_bytes'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.441+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.446+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:35.568+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:35.569+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:35.570+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:35.570+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:35.625+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:35.627+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:35.627+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:35.628+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:35.630+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:35.632+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Connection complete.
[2025-08-04T21:50:35.644+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName1', 'last_name': 'LastName1', 'dob': 'dob1', 'city': 'Durban', 'country': 'Canada'}
[2025-08-04T21:50:35.646+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName2', 'last_name': 'LastName2', 'dob': 'dob2', 'city': 'Cape Town', 'country': 'South Africa'}
[2025-08-04T21:50:35.649+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName3', 'last_name': 'LastName3', 'dob': 'dob3', 'city': 'Johannesburg', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.651+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName4', 'last_name': 'LastName4', 'dob': 'dob4', 'city': 'Montreal', 'country': 'Germany'}
[2025-08-04T21:50:35.651+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName5', 'last_name': 'LastName5', 'dob': 'dob5', 'city': 'London', 'country': 'South Africa'}
[2025-08-04T21:50:35.653+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName6', 'last_name': 'LastName6', 'dob': 'dob6', 'city': 'Toronto', 'country': 'Canada'}
[2025-08-04T21:50:35.654+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName7', 'last_name': 'LastName7', 'dob': 'dob7', 'city': 'Johannesburg', 'country': 'Canada'}
[2025-08-04T21:50:35.656+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName8', 'last_name': 'LastName8', 'dob': 'dob8', 'city': 'London', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.657+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName9', 'last_name': 'LastName9', 'dob': 'dob9', 'city': 'Toronto', 'country': 'India'}
[2025-08-04T21:50:35.663+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName10', 'last_name': 'LastName10', 'dob': 'dob10', 'city': 'London', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.664+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName11', 'last_name': 'LastName11', 'dob': 'dob11', 'city': 'Durban', 'country': 'Canada'}
[2025-08-04T21:50:35.664+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName12', 'last_name': 'LastName12', 'dob': 'dob12', 'city': 'Vancouver', 'country': 'India'}
[2025-08-04T21:50:35.665+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName13', 'last_name': 'LastName13', 'dob': 'dob13', 'city': 'Vancouver', 'country': 'Canada'}
[2025-08-04T21:50:35.666+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName14', 'last_name': 'LastName14', 'dob': 'dob14', 'city': 'Cape Town', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.666+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName15', 'last_name': 'LastName15', 'dob': 'dob15', 'city': 'London', 'country': 'South Africa'}
[2025-08-04T21:50:35.667+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName16', 'last_name': 'LastName16', 'dob': 'dob16', 'city': 'Berlin', 'country': 'India'}
[2025-08-04T21:50:35.667+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName17', 'last_name': 'LastName17', 'dob': 'dob17', 'city': 'London', 'country': 'India'}
[2025-08-04T21:50:35.668+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName18', 'last_name': 'LastName18', 'dob': 'dob18', 'city': 'Montreal', 'country': 'India'}
[2025-08-04T21:50:35.669+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName19', 'last_name': 'LastName19', 'dob': 'dob19', 'city': 'Cape Town', 'country': 'Germany'}
[2025-08-04T21:50:35.669+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName20', 'last_name': 'LastName20', 'dob': 'dob20', 'city': 'London', 'country': 'Germany'}
[2025-08-04T21:50:35.736+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:35.737+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:35.739+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:35.741+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.202+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.215+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.216+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.217+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.266+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.266+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.267+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.268+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.269+0000] {conn.py:1174} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Error receiving network data closing socket
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/conn.py", line 1157, in _recv
    data = self._sock.recv(self.config['sock_chunk_bytes'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:38.277+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:38.283+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.406+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.412+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:38.418+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:38.422+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.449+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.454+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:38.456+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.462+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:38.521+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.522+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:38.523+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:38.525+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.568+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.570+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:38.572+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.574+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:38.732+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.733+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:38.734+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.735+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:38.833+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.836+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:38.837+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.838+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.960+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.973+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.976+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.984+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:39.171+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.173+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:39.174+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.176+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:39.239+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.241+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:39.242+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.244+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:39.925+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.925+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:39.926+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.926+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:40.025+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:40.025+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:40.025+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:40.025+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:40.355+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:40.355+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:40.355+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:40.355+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:41.484+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:41.485+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:41.485+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:41.486+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:41.737+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:41.738+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:41.738+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:41.738+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:43.709+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:43.710+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:43.710+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:43.710+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:44.256+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:44.256+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:44.256+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:44.256+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:45.166+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:45.166+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:45.166+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:45.166+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:51.360+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:51.365+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:51.366+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:51.366+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:51.553+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:51.553+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:51.554+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:51.558+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:52.840+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:52.840+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:52.840+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:52.841+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:51:03.031+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:03.032+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:51:03.032+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:03.033+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:51:03.091+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:03.091+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:51:03.091+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:03.091+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:51:04.978+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:04.978+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:51:04.979+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:04.979+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:51:27.433+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:27.435+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:51:27.435+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:27.435+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:51:32.706+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:32.706+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:51:32.706+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:32.707+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:51:33.019+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:33.019+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:51:33.019+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:33.019+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:51:54.116+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:54.119+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:51:54.120+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:54.121+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:52:06.864+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:06.869+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:52:06.870+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:06.871+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:52:07.994+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:07.996+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:52:07.997+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:07.997+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:52:28.577+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:28.578+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:52:28.579+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:28.579+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:52:33.398+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:33.400+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:52:33.400+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:33.400+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:52:35.644+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 20 record(s) for TopicPartition(topic='artist_data', partition=0): 120004 ms has passed since batch creation
[2025-08-04T21:52:35.646+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 20 record(s) for TopicPartition(topic='artist_data', partition=0): 120004 ms has passed since batch creation
[2025-08-04T21:52:35.646+0000] {artist_kafka_operator.py:51} INFO - 20 transactions sent has been sent to kafka artist_data!
[2025-08-04T21:52:35.661+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-04T21:52:35.662+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=artist_generator, task_id=generator_artist_data, run_id=scheduled__2025-01-05T00:00:00+00:00, execution_date=20250105T000000, start_date=20250804T215031, end_date=20250804T215235
[2025-08-04T21:52:35.694+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-04T21:52:35.704+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T21:52:35.704+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
