[2025-08-04T21:50:36.716+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-04T21:50:36.738+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-11T00:00:00+00:00 [queued]>
[2025-08-04T21:50:36.745+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-11T00:00:00+00:00 [queued]>
[2025-08-04T21:50:36.746+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-04T21:50:36.753+0000] {taskinstance.py:2890} INFO - Executing <Task(ArtistProduceOperator): generator_artist_data> on 2025-01-11 00:00:00+00:00
[2025-08-04T21:50:36.760+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7204) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-04T21:50:36.761+0000] {standard_task_runner.py:72} INFO - Started process 7243 to run task
[2025-08-04T21:50:36.762+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'artist_generator', 'generator_artist_data', 'scheduled__2025-01-11T00:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/artist_generator.py', '--cfg-path', '/tmp/tmphq7ibtgp']
[2025-08-04T21:50:36.769+0000] {standard_task_runner.py:105} INFO - Job 242: Subtask generator_artist_data
[2025-08-04T21:50:36.842+0000] {task_command.py:467} INFO - Running <TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-11T00:00:00+00:00 [running]> on host c4e4284cebf8
[2025-08-04T21:50:36.964+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='artist_generator' AIRFLOW_CTX_TASK_ID='generator_artist_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-11T00:00:00+00:00'
[2025-08-04T21:50:36.967+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-04T21:50:37.293+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.269+0000] {conn.py:1174} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 19092)]>: Error receiving network data closing socket
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/conn.py", line 1157, in _recv
    data = self._sock.recv(self.config['sock_chunk_bytes'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:38.280+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:38.282+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.283+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:38.285+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:38.289+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.08 secs
[2025-08-04T21:50:38.375+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.378+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:38.380+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:38.381+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.18 secs
[2025-08-04T21:50:38.588+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.589+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:38.590+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:38.592+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.32 secs
[2025-08-04T21:50:38.953+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.967+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:38.970+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.973+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.14 secs
[2025-08-04T21:50:39.112+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 40, in execute
    producer = KafkaProducer(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 481, in __init__
    client = self.config['kafka_client'](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
                                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-08-04T21:50:39.157+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=artist_generator, task_id=generator_artist_data, run_id=scheduled__2025-01-11T00:00:00+00:00, execution_date=20250111T000000, start_date=20250804T215036, end_date=20250804T215039
[2025-08-04T21:50:39.242+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-04T21:50:39.246+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 242 for task generator_artist_data (NoBrokersAvailable; 7243)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 40, in execute
    producer = KafkaProducer(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 481, in __init__
    client = self.config['kafka_client'](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
                                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-08-04T21:50:39.282+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-04T21:50:39.327+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T21:50:39.332+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
