[2025-08-04T21:50:31.206+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-04T21:50:31.258+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-08-04T21:50:31.286+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-01T00:00:00+00:00 [queued]>
[2025-08-04T21:50:31.288+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-04T21:50:31.320+0000] {taskinstance.py:2890} INFO - Executing <Task(ArtistProduceOperator): generator_artist_data> on 2025-01-01 00:00:00+00:00
[2025-08-04T21:50:31.336+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7186) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-04T21:50:31.338+0000] {standard_task_runner.py:72} INFO - Started process 7196 to run task
[2025-08-04T21:50:31.340+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'artist_generator', 'generator_artist_data', 'scheduled__2025-01-01T00:00:00+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/artist_generator.py', '--cfg-path', '/tmp/tmp1q2f8iye']
[2025-08-04T21:50:31.355+0000] {standard_task_runner.py:105} INFO - Job 231: Subtask generator_artist_data
[2025-08-04T21:50:31.427+0000] {task_command.py:467} INFO - Running <TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-01T00:00:00+00:00 [running]> on host c4e4284cebf8
[2025-08-04T21:50:31.617+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='artist_generator' AIRFLOW_CTX_TASK_ID='generator_artist_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T00:00:00+00:00'
[2025-08-04T21:50:31.625+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-04T21:50:31.723+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:31.735+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 19092)]>: Broker version identified as 2.6
[2025-08-04T21:50:31.736+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Connection complete.
[2025-08-04T21:50:31.847+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:31.849+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: Connection complete.
[2025-08-04T21:50:31.849+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. 
[2025-08-04T21:50:31.883+0000] {cluster.py:316} ERROR - Topic artist_data not found in cluster metadata
[2025-08-04T21:50:31.989+0000] {cluster.py:316} ERROR - Topic artist_data not found in cluster metadata
[2025-08-04T21:50:32.093+0000] {cluster.py:316} ERROR - Topic artist_data not found in cluster metadata
[2025-08-04T21:50:32.217+0000] {cluster.py:316} ERROR - Topic artist_data not found in cluster metadata
[2025-08-04T21:50:32.405+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName1', 'last_name': 'LastName1', 'dob': 'dob1', 'city': 'Cape Town', 'country': 'United Kingdom'}
[2025-08-04T21:50:32.515+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName2', 'last_name': 'LastName2', 'dob': 'dob2', 'city': 'Munich', 'country': 'Germany'}
[2025-08-04T21:50:32.578+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName3', 'last_name': 'LastName3', 'dob': 'dob3', 'city': 'Manchester', 'country': 'Canada'}
[2025-08-04T21:50:32.605+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName4', 'last_name': 'LastName4', 'dob': 'dob4', 'city': 'Munich', 'country': 'South Africa'}
[2025-08-04T21:50:32.839+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName5', 'last_name': 'LastName5', 'dob': 'dob5', 'city': 'Edinburgh', 'country': 'South Africa'}
[2025-08-04T21:50:35.406+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName6', 'last_name': 'LastName6', 'dob': 'dob6', 'city': 'Hamburg', 'country': 'Canada'}
[2025-08-04T21:50:35.432+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName7', 'last_name': 'LastName7', 'dob': 'dob7', 'city': 'Manchester', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.450+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName8', 'last_name': 'LastName8', 'dob': 'dob8', 'city': 'Toronto', 'country': 'India'}
[2025-08-04T21:50:35.452+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName9', 'last_name': 'LastName9', 'dob': 'dob9', 'city': 'Munich', 'country': 'India'}
[2025-08-04T21:50:35.455+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName10', 'last_name': 'LastName10', 'dob': 'dob10', 'city': 'Johannesburg', 'country': 'Canada'}
[2025-08-04T21:50:35.460+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName11', 'last_name': 'LastName11', 'dob': 'dob11', 'city': 'Manchester', 'country': 'India'}
[2025-08-04T21:50:35.464+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName12', 'last_name': 'LastName12', 'dob': 'dob12', 'city': 'Vancouver', 'country': 'South Africa'}
[2025-08-04T21:50:35.430+0000] {conn.py:1084} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: Error sending request data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/conn.py", line 1075, in send_pending_requests_v2
    total_bytes = self._send_bytes(self._send_buffer)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/conn.py", line 714, in _send_bytes
    sent_bytes = self._sock.send(data[total_sent:])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.469+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName13', 'last_name': 'LastName13', 'dob': 'dob13', 'city': 'Cape Town', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.483+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName14', 'last_name': 'LastName14', 'dob': 'dob14', 'city': 'Durban', 'country': 'Canada'}
[2025-08-04T21:50:35.481+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.484+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName15', 'last_name': 'LastName15', 'dob': 'dob15', 'city': 'Vancouver', 'country': 'Canada'}
[2025-08-04T21:50:35.486+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:35.491+0000] {sender.py:392} ERROR - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Error sending produce request to node 6: KafkaConnectionError: <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.489+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName16', 'last_name': 'LastName16', 'dob': 'dob16', 'city': 'Hamburg', 'country': 'Germany'}
[2025-08-04T21:50:35.493+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName17', 'last_name': 'LastName17', 'dob': 'dob17', 'city': 'Hamburg', 'country': 'South Africa'}
[2025-08-04T21:50:35.492+0000] {sender.py:471} WARNING - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Got error produce response on topic-partition ('artist_data', 0), retrying (inf attempts left). Error: KafkaConnectionError: <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.494+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName18', 'last_name': 'LastName18', 'dob': 'dob18', 'city': 'Vancouver', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.497+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName19', 'last_name': 'LastName19', 'dob': 'dob19', 'city': 'Delhi', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.495+0000] {sender.py:392} ERROR - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Error sending produce request to node 6: KafkaConnectionError: <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.498+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName20', 'last_name': 'LastName20', 'dob': 'dob20', 'city': 'Johannesburg', 'country': 'Germany'}
[2025-08-04T21:50:35.499+0000] {sender.py:471} WARNING - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Got error produce response on topic-partition ('artist_data', 0), retrying (inf attempts left). Error: KafkaConnectionError: <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.501+0000] {sender.py:392} ERROR - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Error sending produce request to node 6: KafkaConnectionError: <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.501+0000] {sender.py:471} WARNING - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Got error produce response on topic-partition ('artist_data', 0), retrying (inf attempts left). Error: KafkaConnectionError: <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.502+0000] {sender.py:392} ERROR - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Error sending produce request to node 6: KafkaConnectionError: <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.502+0000] {sender.py:471} WARNING - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Got error produce response on topic-partition ('artist_data', 0), retrying (inf attempts left). Error: KafkaConnectionError: <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.503+0000] {sender.py:392} ERROR - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Error sending produce request to node 6: KafkaConnectionError: <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.504+0000] {sender.py:471} WARNING - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Got error produce response on topic-partition ('artist_data', 0), retrying (inf attempts left). Error: KafkaConnectionError: <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.507+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:35.510+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Connection complete.
[2025-08-04T21:50:35.611+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:35.612+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:35.612+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:35.613+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:35.700+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:35.701+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:35.701+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:35.702+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.204+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.216+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.220+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.223+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.262+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.265+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.266+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.266+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.268+0000] {conn.py:1174} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Error receiving network data closing socket
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/conn.py", line 1157, in _recv
    data = self._sock.recv(self.config['sock_chunk_bytes'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:38.277+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:38.280+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.419+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.424+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:38.434+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.447+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:38.514+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.517+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:38.518+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.520+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:38.575+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.580+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:38.582+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:38.585+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.622+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.624+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:38.624+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.624+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:38.683+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.902+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.903+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.905+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.946+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:40.242+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:40.242+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:40.243+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:40.243+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:44.046+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:44.047+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:44.047+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:44.047+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:49.270+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:49.271+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:49.272+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:49.272+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:51:03.158+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:03.159+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:51:03.160+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:03.160+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:51:25.497+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:25.506+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:51:25.506+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:25.508+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:51:51.782+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:51.784+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:51:51.784+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:51.785+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:52:21.802+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:21.804+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:52:21.804+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:21.804+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:52:35.331+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 120008 ms has passed since batch creation
[2025-08-04T21:52:35.332+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 2 record(s) for TopicPartition(topic='artist_data', partition=0): 122727 ms has passed since batch creation
[2025-08-04T21:52:35.332+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122759 ms has passed since batch creation
[2025-08-04T21:52:35.332+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122853 ms has passed since batch creation
[2025-08-04T21:52:35.332+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122929 ms has passed since batch creation
[2025-08-04T21:52:35.333+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122929 ms has passed since batch creation
[2025-08-04T21:52:35.333+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122853 ms has passed since batch creation
[2025-08-04T21:52:35.333+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122759 ms has passed since batch creation
[2025-08-04T21:52:35.333+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 2 record(s) for TopicPartition(topic='artist_data', partition=0): 122727 ms has passed since batch creation
[2025-08-04T21:52:35.436+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 14 record(s) for TopicPartition(topic='artist_data', partition=0): 120003 ms has passed since batch creation
[2025-08-04T21:52:35.439+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 14 record(s) for TopicPartition(topic='artist_data', partition=0): 120003 ms has passed since batch creation
[2025-08-04T21:52:35.440+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 120008 ms has passed since batch creation
[2025-08-04T21:52:35.441+0000] {artist_kafka_operator.py:51} INFO - 20 transactions sent has been sent to kafka artist_data!
[2025-08-04T21:52:35.442+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. 
[2025-08-04T21:52:35.467+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-04T21:52:35.468+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=artist_generator, task_id=generator_artist_data, run_id=scheduled__2025-01-01T00:00:00+00:00, execution_date=20250101T000000, start_date=20250804T215031, end_date=20250804T215235
[2025-08-04T21:52:35.515+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-04T21:52:35.556+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T21:52:35.558+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
