[2025-08-04T21:52:16.079+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-04T21:52:16.093+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-08-04T21:52:16.102+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-04-05T00:00:00+00:00 [queued]>
[2025-08-04T21:52:16.102+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-04T21:52:16.108+0000] {taskinstance.py:2890} INFO - Executing <Task(ArtistProduceOperator): generator_artist_data> on 2025-04-05 00:00:00+00:00
[2025-08-04T21:52:16.114+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7564) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-04T21:52:16.115+0000] {standard_task_runner.py:72} INFO - Started process 7571 to run task
[2025-08-04T21:52:16.114+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'artist_generator', 'generator_artist_data', 'scheduled__2025-04-05T00:00:00+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/artist_generator.py', '--cfg-path', '/tmp/tmp5zdmg1fw']
[2025-08-04T21:52:16.116+0000] {standard_task_runner.py:105} INFO - Job 325: Subtask generator_artist_data
[2025-08-04T21:52:16.150+0000] {task_command.py:467} INFO - Running <TaskInstance: artist_generator.generator_artist_data scheduled__2025-04-05T00:00:00+00:00 [running]> on host c4e4284cebf8
[2025-08-04T21:52:16.185+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='artist_generator' AIRFLOW_CTX_TASK_ID='generator_artist_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-05T00:00:00+00:00'
[2025-08-04T21:52:16.185+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-04T21:52:16.194+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:16.195+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:52:16.195+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:16.195+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.05 secs
[2025-08-04T21:52:16.251+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:16.251+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:52:16.251+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:16.252+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.12 secs
[2025-08-04T21:52:16.373+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:16.373+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:52:16.374+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:16.374+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.23 secs
[2025-08-04T21:52:16.606+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:16.606+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:52:16.606+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:16.606+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.45 secs
[2025-08-04T21:52:17.065+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:17.066+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:52:17.066+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:17.066+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.72 secs
[2025-08-04T21:52:17.784+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:17.784+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:52:17.784+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:17.785+0000] {client_async.py:1049} WARNING - No node available during check_version; sleeping 0.41 secs
[2025-08-04T21:52:18.193+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 40, in execute
    producer = KafkaProducer(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 481, in __init__
    client = self.config['kafka_client'](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
                                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-08-04T21:52:18.197+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=artist_generator, task_id=generator_artist_data, run_id=scheduled__2025-04-05T00:00:00+00:00, execution_date=20250405T000000, start_date=20250804T215216, end_date=20250804T215218
[2025-08-04T21:52:18.205+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-04T21:52:18.206+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 325 for task generator_artist_data (NoBrokersAvailable; 7571)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/plugins/artist_kafka_operator.py", line 40, in execute
    producer = KafkaProducer(
               ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 481, in __init__
    client = self.config['kafka_client'](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 262, in __init__
    self.config['api_version'] = self.check_version()
                                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 1074, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2025-08-04T21:52:18.236+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-08-04T21:52:18.244+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T21:52:18.245+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
