[2025-08-04T21:50:31.194+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-04T21:50:31.251+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-02T00:00:00+00:00 [queued]>
[2025-08-04T21:50:31.288+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-02T00:00:00+00:00 [queued]>
[2025-08-04T21:50:31.295+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-04T21:50:31.453+0000] {taskinstance.py:2890} INFO - Executing <Task(ArtistProduceOperator): generator_artist_data> on 2025-01-02 00:00:00+00:00
[2025-08-04T21:50:31.470+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7187) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-04T21:50:31.472+0000] {standard_task_runner.py:72} INFO - Started process 7201 to run task
[2025-08-04T21:50:31.471+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'artist_generator', 'generator_artist_data', 'scheduled__2025-01-02T00:00:00+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/artist_generator.py', '--cfg-path', '/tmp/tmpbiayoy2x']
[2025-08-04T21:50:31.475+0000] {standard_task_runner.py:105} INFO - Job 232: Subtask generator_artist_data
[2025-08-04T21:50:31.602+0000] {task_command.py:467} INFO - Running <TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-02T00:00:00+00:00 [running]> on host c4e4284cebf8
[2025-08-04T21:50:31.765+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='artist_generator' AIRFLOW_CTX_TASK_ID='generator_artist_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-02T00:00:00+00:00'
[2025-08-04T21:50:31.769+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-04T21:50:31.800+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:31.811+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 19092)]>: Broker version identified as 2.6
[2025-08-04T21:50:31.811+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Connection complete.
[2025-08-04T21:50:31.922+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:31.924+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: Connection complete.
[2025-08-04T21:50:31.924+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. 
[2025-08-04T21:50:31.927+0000] {cluster.py:316} ERROR - Topic artist_data not found in cluster metadata
[2025-08-04T21:50:32.031+0000] {cluster.py:316} ERROR - Topic artist_data not found in cluster metadata
[2025-08-04T21:50:32.150+0000] {cluster.py:316} ERROR - Topic artist_data not found in cluster metadata
[2025-08-04T21:50:32.287+0000] {cluster.py:316} ERROR - Topic artist_data not found in cluster metadata
[2025-08-04T21:50:32.547+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName1', 'last_name': 'LastName1', 'dob': 'dob1', 'city': 'Johannesburg', 'country': 'South Africa'}
[2025-08-04T21:50:32.641+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName2', 'last_name': 'LastName2', 'dob': 'dob2', 'city': 'Munich', 'country': 'Germany'}
[2025-08-04T21:50:34.484+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName3', 'last_name': 'LastName3', 'dob': 'dob3', 'city': 'Delhi', 'country': 'South Africa'}
[2025-08-04T21:50:35.385+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName4', 'last_name': 'LastName4', 'dob': 'dob4', 'city': 'Toronto', 'country': 'India'}
[2025-08-04T21:50:35.398+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName5', 'last_name': 'LastName5', 'dob': 'dob5', 'city': 'Berlin', 'country': 'Canada'}
[2025-08-04T21:50:35.400+0000] {conn.py:1174} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: Error receiving network data closing socket
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/conn.py", line 1157, in _recv
    data = self._sock.recv(self.config['sock_chunk_bytes'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.402+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName6', 'last_name': 'LastName6', 'dob': 'dob6', 'city': 'Montreal', 'country': 'India'}
[2025-08-04T21:50:35.437+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName7', 'last_name': 'LastName7', 'dob': 'dob7', 'city': 'Toronto', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.440+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName8', 'last_name': 'LastName8', 'dob': 'dob8', 'city': 'Edinburgh', 'country': 'Canada'}
[2025-08-04T21:50:35.434+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connected> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.446+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:35.444+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName9', 'last_name': 'LastName9', 'dob': 'dob9', 'city': 'Hamburg', 'country': 'India'}
[2025-08-04T21:50:35.452+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName10', 'last_name': 'LastName10', 'dob': 'dob10', 'city': 'Manchester', 'country': 'India'}
[2025-08-04T21:50:35.450+0000] {sender.py:392} ERROR - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Error sending produce request to node 6: KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.456+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName11', 'last_name': 'LastName11', 'dob': 'dob11', 'city': 'Vancouver', 'country': 'Canada'}
[2025-08-04T21:50:35.459+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName12', 'last_name': 'LastName12', 'dob': 'dob12', 'city': 'Berlin', 'country': 'Germany'}
[2025-08-04T21:50:35.458+0000] {sender.py:471} WARNING - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Got error produce response on topic-partition ('artist_data', 0), retrying (inf attempts left). Error: KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.467+0000] {sender.py:392} ERROR - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Error sending produce request to node 6: KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.463+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName13', 'last_name': 'LastName13', 'dob': 'dob13', 'city': 'Manchester', 'country': 'Canada'}
[2025-08-04T21:50:35.471+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName14', 'last_name': 'LastName14', 'dob': 'dob14', 'city': 'Cape Town', 'country': 'United Kingdom'}
[2025-08-04T21:50:35.472+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName15', 'last_name': 'LastName15', 'dob': 'dob15', 'city': 'Edinburgh', 'country': 'Canada'}
[2025-08-04T21:50:35.469+0000] {sender.py:471} WARNING - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Got error produce response on topic-partition ('artist_data', 0), retrying (inf attempts left). Error: KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.482+0000] {sender.py:392} ERROR - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Error sending produce request to node 6: KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.482+0000] {sender.py:471} WARNING - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Got error produce response on topic-partition ('artist_data', 0), retrying (inf attempts left). Error: KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.483+0000] {sender.py:392} ERROR - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Error sending produce request to node 6: KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.484+0000] {sender.py:471} WARNING - <Sender client_id=kafka-python-producer-1 transactional_id=None>: Got error produce response on topic-partition ('artist_data', 0), retrying (inf attempts left). Error: KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:35.479+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName16', 'last_name': 'LastName16', 'dob': 'dob16', 'city': 'Edinburgh', 'country': 'Canada'}
[2025-08-04T21:50:35.489+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName17', 'last_name': 'LastName17', 'dob': 'dob17', 'city': 'Manchester', 'country': 'Canada'}
[2025-08-04T21:50:35.491+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName18', 'last_name': 'LastName18', 'dob': 'dob18', 'city': 'London', 'country': 'India'}
[2025-08-04T21:50:35.492+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName19', 'last_name': 'LastName19', 'dob': 'dob19', 'city': 'Johannesburg', 'country': 'Canada'}
[2025-08-04T21:50:35.497+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName20', 'last_name': 'LastName20', 'dob': 'dob20', 'city': 'Mumbai', 'country': 'Germany'}
[2025-08-04T21:50:35.491+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:35.498+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:35.498+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:35.499+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:35.510+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:35.512+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:35.513+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:35.514+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:35.571+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:35.572+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:35.573+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:35.574+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:35.591+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:35.593+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:35.594+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:35.597+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:35.601+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:35.609+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Connection complete.
[2025-08-04T21:50:35.818+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: connecting to kafka-broker-3:19092 [('172.18.0.7', 19092) IPv4]
[2025-08-04T21:50:35.819+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:35.820+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:35.822+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.200+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.214+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.216+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.218+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.265+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.266+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.266+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.266+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.269+0000] {conn.py:1174} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Error receiving network data closing socket
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/conn.py", line 1157, in _recv
    data = self._sock.recv(self.config['sock_chunk_bytes'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:38.285+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:38.287+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.405+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.410+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:38.416+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:38.419+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.451+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.454+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:38.457+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.469+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:38.523+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.529+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:38.540+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:38.543+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.604+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.605+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:38.605+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.606+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:38.752+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.754+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:38.755+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.758+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:39.002+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.004+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:39.006+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.007+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:39.117+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.119+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:39.119+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.119+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:39.676+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.677+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:39.677+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.677+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:39.679+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.679+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:39.679+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.679+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:39.847+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.847+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:39.847+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.848+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:41.439+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:41.440+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:41.440+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:41.441+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:41.737+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:41.738+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:41.738+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:41.738+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:42.457+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:42.457+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:42.457+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:42.457+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:44.299+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:44.300+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:44.300+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:44.301+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:45.145+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:45.145+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:45.145+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:45.146+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:48.478+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:48.480+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:48.480+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:48.480+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:51.641+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:51.642+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:51.643+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:51.643+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:51.978+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:51.978+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:51.978+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:51.978+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:59.077+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:59.080+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:59.080+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:59.082+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:51:02.649+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:02.649+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:51:02.649+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:02.649+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:51:05.018+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:05.020+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:51:05.020+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:05.020+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:51:24.222+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:24.223+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:51:24.223+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:24.224+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:51:29.557+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:29.558+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:51:29.559+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:29.559+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:51:34.635+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:34.635+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:51:34.636+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:34.636+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:51:57.624+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:57.628+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:51:57.630+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:57.631+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:51:59.753+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:59.753+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:51:59.754+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:59.754+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:52:05.093+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:05.094+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:52:05.095+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:05.096+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:52:27.611+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:27.613+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:52:27.613+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:27.614+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:52:31.306+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:31.306+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:52:31.306+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [IPv4 ('172.18.0.7', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:31.307+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:52:35.366+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 120008 ms has passed since batch creation
[2025-08-04T21:52:35.367+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122100 ms has passed since batch creation
[2025-08-04T21:52:35.367+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 120008 ms has passed since batch creation
[2025-08-04T21:52:35.367+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122773 ms has passed since batch creation
[2025-08-04T21:52:35.367+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122821 ms has passed since batch creation
[2025-08-04T21:52:35.368+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122821 ms has passed since batch creation
[2025-08-04T21:52:35.368+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122773 ms has passed since batch creation
[2025-08-04T21:52:35.368+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 1 record(s) for TopicPartition(topic='artist_data', partition=0): 122100 ms has passed since batch creation
[2025-08-04T21:52:35.401+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 16 record(s) for TopicPartition(topic='artist_data', partition=0): 120002 ms has passed since batch creation
[2025-08-04T21:52:35.401+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 16 record(s) for TopicPartition(topic='artist_data', partition=0): 120002 ms has passed since batch creation
[2025-08-04T21:52:35.403+0000] {artist_kafka_operator.py:51} INFO - 20 transactions sent has been sent to kafka artist_data!
[2025-08-04T21:52:35.422+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-04T21:52:35.424+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=artist_generator, task_id=generator_artist_data, run_id=scheduled__2025-01-02T00:00:00+00:00, execution_date=20250102T000000, start_date=20250804T215031, end_date=20250804T215235
[2025-08-04T21:52:35.496+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-04T21:52:35.542+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T21:52:35.545+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
