[2025-08-04T21:50:36.150+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-08-04T21:50:36.186+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-09T00:00:00+00:00 [queued]>
[2025-08-04T21:50:36.196+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-09T00:00:00+00:00 [queued]>
[2025-08-04T21:50:36.197+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-08-04T21:50:36.331+0000] {taskinstance.py:2890} INFO - Executing <Task(ArtistProduceOperator): generator_artist_data> on 2025-01-09 00:00:00+00:00
[2025-08-04T21:50:36.371+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'artist_generator', 'generator_artist_data', 'scheduled__2025-01-09T00:00:00+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/artist_generator.py', '--cfg-path', '/tmp/tmprqy3h1qk']
[2025-08-04T21:50:36.383+0000] {standard_task_runner.py:105} INFO - Job 238: Subtask generator_artist_data
[2025-08-04T21:50:36.375+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7194) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-04T21:50:36.388+0000] {standard_task_runner.py:72} INFO - Started process 7229 to run task
[2025-08-04T21:50:36.495+0000] {task_command.py:467} INFO - Running <TaskInstance: artist_generator.generator_artist_data scheduled__2025-01-09T00:00:00+00:00 [running]> on host c4e4284cebf8
[2025-08-04T21:50:36.589+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='artist_generator' AIRFLOW_CTX_TASK_ID='generator_artist_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-09T00:00:00+00:00'
[2025-08-04T21:50:36.590+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-08-04T21:50:36.643+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:36.652+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <checking_api_versions_recv> [IPv4 ('172.18.0.9', 19092)]>: Broker version identified as 2.6
[2025-08-04T21:50:36.657+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Connection complete.
[2025-08-04T21:50:36.782+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:36.784+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:36.785+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:36.788+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:36.849+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:36.850+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:36.851+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:36.852+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:36.910+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:36.911+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Connection complete.
[2025-08-04T21:50:36.912+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. 
[2025-08-04T21:50:36.939+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName1', 'last_name': 'LastName1', 'dob': 'dob1', 'city': 'London', 'country': 'South Africa'}
[2025-08-04T21:50:36.947+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName2', 'last_name': 'LastName2', 'dob': 'dob2', 'city': 'Bangalore', 'country': 'United Kingdom'}
[2025-08-04T21:50:36.948+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName3', 'last_name': 'LastName3', 'dob': 'dob3', 'city': 'Johannesburg', 'country': 'United Kingdom'}
[2025-08-04T21:50:36.949+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName4', 'last_name': 'LastName4', 'dob': 'dob4', 'city': 'Hamburg', 'country': 'South Africa'}
[2025-08-04T21:50:36.949+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName5', 'last_name': 'LastName5', 'dob': 'dob5', 'city': 'Cape Town', 'country': 'Germany'}
[2025-08-04T21:50:36.950+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName6', 'last_name': 'LastName6', 'dob': 'dob6', 'city': 'Durban', 'country': 'India'}
[2025-08-04T21:50:36.952+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName7', 'last_name': 'LastName7', 'dob': 'dob7', 'city': 'Edinburgh', 'country': 'South Africa'}
[2025-08-04T21:50:36.953+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName8', 'last_name': 'LastName8', 'dob': 'dob8', 'city': 'Mumbai', 'country': 'Germany'}
[2025-08-04T21:50:36.955+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName9', 'last_name': 'LastName9', 'dob': 'dob9', 'city': 'London', 'country': 'South Africa'}
[2025-08-04T21:50:36.956+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName10', 'last_name': 'LastName10', 'dob': 'dob10', 'city': 'London', 'country': 'India'}
[2025-08-04T21:50:36.962+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName11', 'last_name': 'LastName11', 'dob': 'dob11', 'city': 'Johannesburg', 'country': 'South Africa'}
[2025-08-04T21:50:36.970+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName12', 'last_name': 'LastName12', 'dob': 'dob12', 'city': 'Munich', 'country': 'South Africa'}
[2025-08-04T21:50:36.972+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName13', 'last_name': 'LastName13', 'dob': 'dob13', 'city': 'Berlin', 'country': 'South Africa'}
[2025-08-04T21:50:36.973+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName14', 'last_name': 'LastName14', 'dob': 'dob14', 'city': 'Cape Town', 'country': 'Canada'}
[2025-08-04T21:50:36.974+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName15', 'last_name': 'LastName15', 'dob': 'dob15', 'city': 'Berlin', 'country': 'Germany'}
[2025-08-04T21:50:36.975+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName16', 'last_name': 'LastName16', 'dob': 'dob16', 'city': 'Mumbai', 'country': 'South Africa'}
[2025-08-04T21:50:36.980+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName17', 'last_name': 'LastName17', 'dob': 'dob17', 'city': 'Toronto', 'country': 'United Kingdom'}
[2025-08-04T21:50:36.998+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName18', 'last_name': 'LastName18', 'dob': 'dob18', 'city': 'Bangalore', 'country': 'United Kingdom'}
[2025-08-04T21:50:37.016+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName19', 'last_name': 'LastName19', 'dob': 'dob19', 'city': 'Montreal', 'country': 'Canada'}
[2025-08-04T21:50:37.030+0000] {artist_kafka_operator.py:48} INFO - Sent transaction {'first_name': 'FirstName20', 'last_name': 'LastName20', 'dob': 'dob20', 'city': 'Cape Town', 'country': 'South Africa'}
[2025-08-04T21:50:38.203+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.215+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.218+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.226+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.261+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.262+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.262+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.263+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.268+0000] {conn.py:1174} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Error receiving network data closing socket
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/conn.py", line 1157, in _recv
    data = self._sock.recv(self.config['sock_chunk_bytes'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:38.287+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connected> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: [Errno 104] Connection reset by peer
[2025-08-04T21:50:38.289+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.357+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.358+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.360+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.363+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.405+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.407+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:38.414+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:38.419+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.435+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.445+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:38.452+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.455+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:38.526+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: connecting to kafka-broker-1:19092 [('172.18.0.9', 19092) IPv4]
[2025-08-04T21:50:38.527+0000] {conn.py:429} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Connect attempt returned error 111. Disconnecting.
[2025-08-04T21:50:38.527+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2025-08-04T21:50:38.528+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.570+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.572+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.573+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.574+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:38.620+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.621+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:38.622+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.624+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:38.809+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.815+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:38.818+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.822+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:38.948+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:38.952+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:38.960+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:38.965+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:39.047+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.051+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:39.051+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.052+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:39.202+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.205+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:39.206+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.208+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:39.800+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.800+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:39.800+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.801+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:39.803+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.803+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:39.803+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.803+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:39.916+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:39.917+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:39.917+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:39.917+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:41.186+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:41.186+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:41.186+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:41.186+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:41.214+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:41.214+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:41.214+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:41.214+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:41.555+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:41.556+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:41.556+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:41.557+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:44.527+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:44.527+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:44.527+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:44.527+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:44.669+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:44.670+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:44.670+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:44.670+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:50:44.935+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:44.935+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:44.935+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:44.935+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:50.105+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:50.106+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:50:50.106+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:50.106+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:50:51.422+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:51.423+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:50:51.423+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:51.423+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:50:52.278+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:50:52.278+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:50:52.278+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:50:52.279+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:51:03.255+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:03.256+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:51:03.257+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:03.257+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:51:03.346+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:03.346+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:51:03.346+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:03.347+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:51:05.994+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:05.994+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:51:05.994+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:05.995+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:51:30.640+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:30.641+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:51:30.642+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:30.642+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:51:31.452+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:31.453+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:51:31.454+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:31.454+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:51:32.581+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:32.581+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:51:32.581+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:32.582+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:51:56.019+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:56.022+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:51:56.022+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:56.023+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:51:58.790+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:51:58.790+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:51:58.790+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:51:58.790+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:52:08.313+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-2:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:08.315+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-2:19092 (0)
[2025-08-04T21:52:08.315+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=5 host=kafka-broker-2:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:08.315+0000] {client_async.py:388} WARNING - Node 5 connection failed -- refreshing metadata
[2025-08-04T21:52:28.558+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-3:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:28.560+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: DNS lookup failed for kafka-broker-3:19092 (0)
[2025-08-04T21:52:28.560+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=6 host=kafka-broker-3:19092 <connecting> [unspecified None]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:28.560+0000] {client_async.py:388} WARNING - Node 6 connection failed -- refreshing metadata
[2025-08-04T21:52:33.922+0000] {conn.py:1516} WARNING - DNS lookup failed for kafka-broker-1:19092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2025-08-04T21:52:33.922+0000] {conn.py:323} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: DNS lookup failed for kafka-broker-1:19092 (0)
[2025-08-04T21:52:33.922+0000] {conn.py:945} ERROR - <BrokerConnection client_id=kafka-python-producer-1, node_id=4 host=kafka-broker-1:19092 <connecting> [IPv4 ('172.18.0.9', 19092)]>: Closing connection. KafkaConnectionError: DNS failure
[2025-08-04T21:52:33.922+0000] {client_async.py:388} WARNING - Node 4 connection failed -- refreshing metadata
[2025-08-04T21:52:36.944+0000] {record_accumulator.py:133} WARNING - Failed to produce messages to topic-partition ('artist_data', 0) with base offset -1: KafkaTimeoutError: Expiring 20 record(s) for TopicPartition(topic='artist_data', partition=0): 120005 ms has passed since batch creation
[2025-08-04T21:52:36.944+0000] {record_accumulator.py:591} WARNING - KafkaTimeoutError: Expiring 20 record(s) for TopicPartition(topic='artist_data', partition=0): 120005 ms has passed since batch creation
[2025-08-04T21:52:36.945+0000] {artist_kafka_operator.py:51} INFO - 20 transactions sent has been sent to kafka artist_data!
[2025-08-04T21:52:36.954+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-08-04T21:52:36.954+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=artist_generator, task_id=generator_artist_data, run_id=scheduled__2025-01-09T00:00:00+00:00, execution_date=20250109T000000, start_date=20250804T215036, end_date=20250804T215236
[2025-08-04T21:52:37.013+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-08-04T21:52:37.024+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T21:52:37.024+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
